apps/akromdev/urls.py
from django.urls import path
from .views.home_view import IndexView
from .views.contact_view import ContactView
from .views.about_view import AboutView

from .views.video_view import (
    VideoView,
    VideoDetailView,
    VideoCreateView,
    VideoDeleteView,
    VideoUpdateView,
    video_like,
)
from .views.picture_view import (
    PictureView,
    PictureDetailView,
    PictureCreateView,
    PictureDeleteView,
    PictureUpdateView,
)
from .views.audio_view import (
    AudioView,
    AudioDetailView,
    AudioCreateView,
    AudioUpdateView,
    AudioDeleteView,
)
from .views.blog_view import (
    BlogPostDetailView,
    BlogPostView,
    UserPostView,
    PostUpdateView,
    PostDeleteView,
    PostCreateView,
)


app_name = "akromdev"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("about/", AboutView.as_view(), name="about"),
    path("pictures/", PictureView.as_view(), name="pictures"),
    path("picture-create/", PictureCreateView.as_view(), name="picture-create"),
    path(
        "picture-detail/<str:slug>", PictureDetailView.as_view(), name="picture-detail"
    ),
    path(
        "picture-update/<str:slug>", PictureUpdateView.as_view(), name="picture-update"
    ),
    path(
        "picture-delete/<str:slug>", PictureDeleteView.as_view(), name="picture-delete"
    ),
    path("blog-posts/", BlogPostView.as_view(), name="posts"),
    path(
        "blog-post-detail/<str:slug>", BlogPostDetailView.as_view(), name="post-detail"
    ),
    path("user-posts/<str:username>", UserPostView.as_view(), name="user-posts"),
    path("post-update/<str:slug>", PostUpdateView.as_view(), name="post-update"),
    path("post-delete/<str:slug>", PostDeleteView.as_view(), name="post-delete"),
    path("post-create/", PostCreateView.as_view(), name="post-create"),
    path("videos/", VideoView.as_view(), name="videos"),
    path("video-create/", VideoCreateView.as_view(), name="video-create"),
    path("video-detail/<str:slug>", VideoDetailView.as_view(), name="video-detail"),
    path("video-update/<str:slug>", VideoUpdateView.as_view(), name="video-update"),
    path("video-delete/<str:slug>", VideoDeleteView.as_view(), name="video-delete"),
    path("video-like/<str:slug>", video_like, name="video-like"),
    path("audios/", AudioView.as_view(), name="audios"),
    path("audio-create/", AudioCreateView.as_view(), name="audio-create"),
    path("audio-detail/<str:slug>", AudioDetailView.as_view(), name="audio-detail"),
    path("audio-update/<str:slug>", AudioUpdateView.as_view(), name="audio-update"),
    path("audio-delete/<str:slug>", AudioDeleteView.as_view(), name="audio-delete"),
]

apps/users/urls.py
from django.urls import path
from .views import (
    SignUpView,
    SignInView,
    SignOutView,
    UserAccountView,
    UserProfileView,
    user_follow,
    user_unfollow,
    user_folowers,
    user_folowings,
)


app_name = "users"

urlpatterns = [
    path("sign_up/", SignUpView.as_view(), name="sign-up"),
    path("sign-in/", SignInView.as_view(), name="sign-in"),
    path("sign-out/", SignOutView.as_view(), name="sign-out"),
    path("akromdev-user-account/", UserAccountView.as_view(), name="user-account"),
    path(
        "akromdev-user-profile/<str:username>",
        UserProfileView.as_view(),
        name="user-profile",
    ),
    path("user-follow/<str:username>", user_follow, name="user-follow"),
    path("user-unfollow/<str:username>", user_unfollow, name="user-unfollow"),
    path("user-folowers/<str:username>", user_folowers, name="user-folowers"),
    path("user-folowings/<str:username>", user_folowings, name="user-folowings"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from graphene_django.views import GraphQLView

from .swagger_schema import swagger_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls, name="admin_panel"),
    path("", include("apps.akromdev.urls")),
    path("users/", include("apps.users.urls")),
    path("graphql/", GraphQLView.as_view(graphiql=True)),
]

urlpatterns += swagger_urlpatterns

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/akromdev/forms/picture_form.py
from django import forms
from apps.akromdev.models.picture_model import Picture


class PictureCreateForm(forms.Form):
    image = forms.ImageField(
        widget=forms.FileInput(
            attrs={"type": "file", "name": "image", "class": "form-control"}
        )
    )
    description = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={"type": "text", "name": "description", "class": "form-control"}
        ),
    )


class PictureUpdateForm(forms.ModelForm):
    image = forms.ImageField(
        widget=forms.FileInput(
            attrs={"type": "file", "name": "image", "class": "form-control"}
        )
    )
    description = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={"type": "text", "name": "description", "class": "form-control"}
        ),
    )

    class Meta:
        model = Picture
        fields = ("image", "description")

apps/akromdev/views/picture_view.py
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse
from django.contrib import messages
from apps.akromdev.models.picture_model import Picture
from apps.akromdev.forms.picture_form import PictureCreateForm, PictureUpdateForm
from apps.users.models import UserAccount
from apps.akromdev.utils import is_photo


class PictureView(ListView):
    model = Picture
    template_name = "picture/pictures.html"
    context_object_name = "pictures"


class PictureDetailView(View):
    def get(self, request, slug):
        pictures = Picture.objects.all().order_by("-created_at")
        picture = get_object_or_404(pictures, slug=slug)
        return render(
            request,
            "picture/picture-detail.html",
            {"picture": picture, "pictures": pictures},
        )


class PictureCreateView(View):
    def get(self, request):
        form = PictureCreateForm()
        return render(request, "picture/picture-create.html", {"form": form})

    def post(self, request):
        form = PictureCreateForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            image = form.cleaned_data.get("image")

            if is_photo(str(image.name)):
                Picture.objects.create(
                    author=UserAccount.objects.get(user=request.user),
                    image=image,
                    description=form.cleaned_data.get("description"),
                )
                messages.success(request, "Successfully created picture")
                return redirect("akromdev:picture-create")

            messages.error(request, "Your phot are not valid !")
            return redirect("akromdev:picture-create")

        messages.error(request, "Error in your fields !")
        return redirect("akromdev:picture-create")


class PictureUpdateView(View):
    def get(self, request, slug):
        picture = get_object_or_404(Picture, slug=slug)
        form = PictureUpdateForm(instance=picture)
        return render(
            request, "picture/picture-update.html", {"form": form, "picture": picture}
        )

    def post(self, request, slug):
        picture = Picture.objects.filter(slug=slug)
        form = PictureUpdateForm(
            data=request.POST,
            instance=picture.first(),
        )
        if form.is_valid():
            picture.update(
                author=get_object_or_404(UserAccount, user=request.user),
                description=form.cleaned_data.get("description"),
            )

            messages.success(request, "Successfully updated picture")
            return redirect(
                reverse(
                    "akromdev:picture-update", kwargs={"slug": picture.first().slug}
                )
            )

        messages.error(request, "Your fields are not valid !")
        return redirect(
            reverse("akromdev:picture-update", kwargs={"slug": picture.first().slug})
        )


class PictureDeleteView(View):
    def get(self, request, slug):
        return render(
            request,
            "picture/picture-delete.html",
            {"picture": get_object_or_404(Picture, slug=slug)},
        )

    def post(self, request, slug):
        get_object_or_404(Picture, slug=slug).delete()
        return redirect("akromdev:pictures")

templates/picture/picture-create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="col-md-10 mx-auto col-lg-5">
        <div class="modal-header p-5 pb-4 border-bottom-0 bg-light">
          <!-- <h5 class="modal-title">Modal title</h5> -->
          <h3 class="fw-bold mb-0">Picture Create</h3>
          <a href="{% url 'akromdev:pictures' %}" class="btn-close"></a>
      </div>
        <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'akromdev:picture-create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-12">
                <label for="avatar" class="form-label">Image</label>
                {{ form.image }}
              <div class="invalid-feedback">
                Enter valid image
              </div>
            </div>

            
          <div class="form-floating mb-3 mt-5">
            {{ form.description }}
            <label for="floatingInput">Description</label>
          </div>

          <button class="w-100 btn btn-lg btn-primary mt-5" type="submit">Create</button>
          <hr class="my-4">

        </form>

      </div>
</div>
{% endblock %}

templates/picture/picture-delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ picture.title }} Delete {% endblock %}
{% block content %}
<div class="container">
    <div class="modal modal-sheet position-static d-block bg-white py-5" tabindex="-1" role="dialog" id="modalSheet">
        <div class="modal-dialog" role="document">
          <div class="modal-content rounded-6 shadow">
            <div class="modal-header border-bottom-0">
              <h5 class="modal-title">{{ picture.title }}</h5>
              <a href="{% url 'akromdev:picture-detail' picture.slug %}" class="btn-close"></a>
            </div>
            <div class="modal-body py-0">
              <p>{{ picture.content }}</p>
              {% if picture.description %}
                <small>{{ video.description }}</small>
              {% endif %}
            </div>
            <div class="modal-footer flex-column border-top-0">
              <a href="{% url 'akromdev:picture-detail' picture.slug %}" class="btn btn-lg btn-outline-primary w-100 mx-0 mb-2">Cansel</a>
              <form action="{% url 'akromdev:picture-delete' picture.slug %}" method="post" class="btn btn-lg btn-outline-danger w-100 mx-0">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-outline-danger w-100 mx-0">Delete</button>
              </form>
            </div>
          </div>
        </div>
      </div>
</div>
{% endblock %}

templates/picture/picture-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ picture.slug }} {% endblock %}
{% block content %}
<div class="container mt-5">
  <div class="modal position-static d-block bg-white py-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-5 shadow">
        <div class="modal-header p-5 pb-4 border-bottom-0">
          <!-- <h5 class="modal-title">Modal title</h5> -->
          <a href="{% url 'akromdev:pictures' %}" class="btn-close"></a>
        </div>
  
        <div class="modal-body p-5 pt-0">
          <img src="{{ picture.image.url }}" alt="" class="img-fluid">
          {% if picture.description %}
            <div class="mt-3">
              <p>{{ picture.description }}</p>
            </div>
          {% endif %}
          <div class="mt-3">
            <a href="{% url 'users:user-profile' picture.author.username %}" class="nav-link text-dark">
              <img src="{{ picture.author.avatar.url }}" alt="" width="35" height="35" class="img-fluid" style="border-radius: 50%;">
              <span>{{ picture.author.first_name }} {{ picture.author.last_name }}</span>
            </a>
          </div>
          <div>
            <a href="{{ picture.image.url }}" class="w-100 btn btn-lg btn-outline-secondary mt-5" download="">Download</a>
            {% if request.user.account.first == picture.author %}
              <a href="{% url 'akromdev:picture-update' picture.slug %}" class="w-100 btn btn-lg btn-outline-success mt-3" type="submit">Update</a>
              <a href="{% url 'akromdev:picture-delete' picture.slug %}" class="w-100 btn btn-lg btn-outline-danger mt-3" type="submit">Delete</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container mt-5">
    <div class="tab-pane fade active show" id="nav-photos" role="tabpanel" aria-labelledby="nav-photos-tab">
        <div class="row" data-masonry="{&quot;percentPosition&quot;: true }">
            {% for picture in pictures %}
              <div class="col-sm-6 col-lg-4 mb-4">
                <div class="card">
                  <a href="{% url 'akromdev:picture-detail' picture.slug %}">
                    <img src="{{ picture.image.url }}" alt="img" class="bd-placeholder-img card-img" width="100%" height="260" role="img">
                  </a>
                </div>
              </div>
            {% empty %}
                <h1>Now Pictures</h1>
            {% endfor %}
      </div>
    </div>
</div>
</div>
{% endblock %}

templates/picture/picture-update.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ picture.title }} Update {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="col-md-10 mx-auto col-lg-5">
        <div class="modal-header p-5 pb-4 border-bottom-0 bg-light">
            <!-- <h5 class="modal-title">Modal title</h5> -->
            <h3 class="fw-bold mb-0">`{{ picture.title }}` Update</h3>
            <a href="{% url 'akromdev:picture-detail' picture.slug %}" class="btn-close" ></a>
          </div>
        <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'akromdev:picture-update' picture.slug %}" method="POST">
            {% csrf_token %}
            
          <div class="form-floating mb-3 mt-5">
            {{ form.description }}
            <label for="floatingInput">Description</label>
            <div class="invalid-feedback">
                Enter valid description
              </div>
          </div>

          <div>
            <button class="w-100 btn btn-lg btn-primary mt-5" type="submit">Update</button>
            <a href="{% url 'akromdev:picture-detail' picture.slug %}" class="w-100 btn btn-lg btn-outline-secondary mt-3" type="submit">Cansel</a>
          </div>
          <hr class="my-4">

        </form>

      </div>
</div>
{% endblock %}

templates/picture/pictures.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Pictures {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="tab-pane fade active show" id="nav-photos" role="tabpanel" aria-labelledby="nav-photos-tab">
        <div class="row" data-masonry="{&quot;percentPosition&quot;: true }">
            {% for picture in pictures %}
              <div class="col-sm-6 col-lg-4 mb-4">
                <div class="card">
                  <a href="{% url 'akromdev:picture-detail' picture.slug %}">
                    <img src="{{ picture.image.url }}" alt="img" class="bd-placeholder-img card-img" width="100%" height="260" role="img">
                  </a>
                </div>
              </div>
            {% empty %}
                <h1>Now Pictures</h1>
            {% endfor %}
      </div>
    </div>
</div>
{% endblock %}