apps/akromdev/urls.py
from django.urls import path
from .views.home_view import IndexView
from .views.contact_view import ContactView
from .views.about_view import AboutView

from .views.video_view import (
    VideoView,
    VideoDetailView,
    VideoCreateView,
    VideoDeleteView,
    VideoUpdateView,
    video_like,
)
from .views.picture_view import (
    PictureView,
    PictureDetailView,
    PictureCreateView,
    PictureDeleteView,
    PictureUpdateView,
)
from .views.audio_view import (
    AudioView,
    AudioDetailView,
    AudioCreateView,
    AudioUpdateView,
    AudioDeleteView,
)
from .views.blog_view import (
    BlogPostDetailView,
    BlogPostView,
    UserPostView,
    PostUpdateView,
    PostDeleteView,
    PostCreateView,
)


app_name = "akromdev"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("about/", AboutView.as_view(), name="about"),
    path("pictures/", PictureView.as_view(), name="pictures"),
    path("picture-create/", PictureCreateView.as_view(), name="picture-create"),
    path(
        "picture-detail/<str:slug>", PictureDetailView.as_view(), name="picture-detail"
    ),
    path(
        "picture-update/<str:slug>", PictureUpdateView.as_view(), name="picture-update"
    ),
    path(
        "picture-delete/<str:slug>", PictureDeleteView.as_view(), name="picture-delete"
    ),
    path("blog-posts/", BlogPostView.as_view(), name="posts"),
    path(
        "blog-post-detail/<str:slug>", BlogPostDetailView.as_view(), name="post-detail"
    ),
    path("user-posts/<str:username>", UserPostView.as_view(), name="user-posts"),
    path("post-update/<str:slug>", PostUpdateView.as_view(), name="post-update"),
    path("post-delete/<str:slug>", PostDeleteView.as_view(), name="post-delete"),
    path("post-create/", PostCreateView.as_view(), name="post-create"),
    path("videos/", VideoView.as_view(), name="videos"),
    path("video-create/", VideoCreateView.as_view(), name="video-create"),
    path("video-detail/<str:slug>", VideoDetailView.as_view(), name="video-detail"),
    path("video-update/<str:slug>", VideoUpdateView.as_view(), name="video-update"),
    path("video-delete/<str:slug>", VideoDeleteView.as_view(), name="video-delete"),
    path("video-like/<str:slug>", video_like, name="video-like"),
    path("audios/", AudioView.as_view(), name="audios"),
    path("audio-create/", AudioCreateView.as_view(), name="audio-create"),
    path("audio-detail/<str:slug>", AudioDetailView.as_view(), name="audio-detail"),
    path("audio-update/<str:slug>", AudioUpdateView.as_view(), name="audio-update"),
    path("audio-delete/<str:slug>", AudioDeleteView.as_view(), name="audio-delete"),
]

apps/users/urls.py
from django.urls import path
from .views import (
    SignUpView,
    SignInView,
    SignOutView,
    UserAccountView,
    UserProfileView,
    user_follow,
    user_unfollow,
    user_folowers,
    user_folowings,
)


app_name = "users"

urlpatterns = [
    path("sign_up/", SignUpView.as_view(), name="sign-up"),
    path("sign-in/", SignInView.as_view(), name="sign-in"),
    path("sign-out/", SignOutView.as_view(), name="sign-out"),
    path("akromdev-user-account/", UserAccountView.as_view(), name="user-account"),
    path(
        "akromdev-user-profile/<str:username>",
        UserProfileView.as_view(),
        name="user-profile",
    ),
    path("user-follow/<str:username>", user_follow, name="user-follow"),
    path("user-unfollow/<str:username>", user_unfollow, name="user-unfollow"),
    path("user-folowers/<str:username>", user_folowers, name="user-folowers"),
    path("user-folowings/<str:username>", user_folowings, name="user-folowings"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from graphene_django.views import GraphQLView

from .swagger_schema import swagger_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls, name="admin_panel"),
    path("", include("apps.akromdev.urls")),
    path("users/", include("apps.users.urls")),
    path("graphql/", GraphQLView.as_view(graphiql=True)),
]

urlpatterns += swagger_urlpatterns

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/akromdev/forms/audio_form.py
from django import forms
from apps.akromdev.models.audio_model import Audio


class AudioCreateForm(forms.ModelForm):
    title = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"type": "text", "name": "title", "class": "form-control"}
        ),
    )
    description = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "type": "description",
                "name": "description",
                "class": "form-control",
            }
        ),
    )
    cover = forms.ImageField(
        widget=forms.FileInput(
            attrs={"type": "file", "name": "cover", "class": "form-control"}
        )
    )
    audio = forms.FileField(
        widget=forms.FileInput(
            attrs={"type": "file", "name": "audio", "class": "form-control"}
        )
    )

    class Meta:
        model = Audio
        fields = ("title", "description", "cover", "audio", "category")


class AudioUpdateForm(forms.ModelForm):
    title = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"type": "text", "name": "title", "class": "form-control"}
        ),
    )
    description = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "type": "description",
                "name": "description",
                "class": "form-control",
            }
        ),
    )

    class Meta:
        model = Audio
        fields = ("title", "description", "category")

apps/akromdev/views/audio_view.py
from django.views import View
from django.views.generic import DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from apps.akromdev.models.audio_model import Audio
from apps.akromdev.forms.audio_form import AudioCreateForm, AudioUpdateForm
from apps.users.models import UserAccount
from apps.akromdev.utils import is_photo, is_audio

import markdown2


class AudioView(View):
    def get(self, request):
        audios = Audio.objects.all().order_by("-created_at")
        return render(request, "audio/audios.html", {"audios": audios})


class AudioDetailView(View):
    def get(self, request, slug):
        if request.user.is_authenticated:
            audio = get_object_or_404(Audio, slug=slug)
            audios = Audio.objects.filter(category=audio.category).order_by(
                "-created_at"
            )
            return render(
                request,
                "audio/audio-detail.html",
                {
                    "audio_description_html": markdown2.markdown(audio.description),
                    "audio": audio,
                    "audios": audios,
                },
            )
        return redirect("users:sign-up")


class AudioCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = AudioCreateForm()
        return render(request, "audio/audio-create.html", {"form": form})

    def post(self, request):
        form = AudioCreateForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            cover = form.cleaned_data.get("cover")
            audio = form.cleaned_data.get("audio")

            if is_photo(cover.name):
                if is_audio(audio.name):
                    Audio.objects.create(
                        author=get_object_or_404(UserAccount, user=request.user),
                        title=form.cleaned_data.get("title"),
                        description=form.cleaned_data.get("description"),
                        category=form.cleaned_data.get("category"),
                        cover=cover,
                        audio=audio,
                    )
                    messages.success(request, "Successfully created audio.")
                    return redirect("akromdev:audio-create")

                messages.warning(request, "Your audio are not valid !")
                return redirect("akromdev:audio-create")

            messages.warning(request, "Your phot are not valid !")
            return redirect("akromdev:audio-create")

        messages.error(request, "Your fields are not valid")
        return redirect("akromdev:audio-create")


class AudioUpdateView(View):
    def get(self, request, slug):
        audio = get_object_or_404(Audio, slug=slug)
        form = AudioUpdateForm(instance=audio)
        return render(
            request, "audio/audio-update.html", {"form": form, "audio": audio}
        )

    def post(self, request, slug):
        audio = Audio.objects.filter(slug=slug)

        form = AudioUpdateForm(
            data=request.POST,
            instance=audio.first(),
        )
        if form.is_valid():
            audio.update(
                title=form.cleaned_data.get("title"),
                description=form.cleaned_data.get("description"),
                category=form.cleaned_data.get("category"),
            )

            messages.success(request, "Successfully updated Audio.")
            return redirect(
                reverse("akromdev:audio-update", kwargs={"slug": audio.first().slug})
            )

        messages.error("Your fields are not valid !")
        return redirect(
            reverse("akromdev:audio-update", kwargs={"slug": audio.first().slug})
        )


class AudioDeleteView(DeleteView):
    def get(self, request, slug):
        return render(
            request,
            "audio/audio-delete.html",
            {"audio": get_object_or_404(Audio, slug=slug)},
        )

    def post(self, request, slug):
        get_object_or_404(Audio, slug=slug).delete()
        return redirect("akromdev:audios")

templates/audio/audio-create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Audio Create {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="col-md-10 mx-auto col-lg-5">
        <div class="modal-header p-5 pb-4 border-bottom-0 bg-light">
          <!-- <h5 class="modal-title">Modal title</h5> -->
          <h3 class="fw-bold mb-0">Audio Create</h3>
          <a href="{% url 'akromdev:audios' %}" class="btn-close"></a>
        </div>
        <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'akromdev:audio-create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
          <div class="form-floating mb-3">
            {{ form.title }}
            <label for="floatingInput">title</label>
          </div>

          <div class="form-floating mb-3">
            {{ form.description }}
            <label for="floatingInput">Description</label>
          </div>

          <div class="form-floating mb-3">
            {{ form.category }}
          </div>

          <div class="col-12">
              <label for="avatar" class="form-label">Cover</label>
              {{ form.cover }}
            <div class="invalid-feedback">
              Enter valid image
            </div>
          </div>

          <div class="col-12">
              <label for="avatar" class="form-label">Audio</label>
              {{ form.audio }}
            <div class="invalid-feedback">
              Enter valid audio
            </div>
          </div>
        
          <button class="w-100 btn btn-lg btn-primary mt-5" type="submit">Create</button>
          <hr class="my-4">

          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
        </form>

      </div>
</div>
{% endblock %}

templates/audio/audio-delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ audio.title }} Delete {% endblock %}
{% block content %}
<div class="container">
    <div class="modal modal-sheet position-static d-block bg-white py-5" tabindex="-1" role="dialog" id="modalSheet">
        <div class="modal-dialog" role="document">
          <div class="modal-content rounded-6 shadow">
            <div class="modal-header border-bottom-0">
              <h5 class="modal-title">{{ audio.title }}</h5>
              <a href="{% url 'akromdev:audio-detail' audio.slug %}" class="btn-close"></a>
            </div>
            <div class="modal-body py-0">
              <p>{{ audio.content }}</p>
              {% if audio.description %}
                <small>{{ video.description }}</small>
              {% endif %}
            </div>
            <div class="modal-footer flex-column border-top-0">
              <form action="{% url 'akromdev:audio-delete' audio.slug %}" method="post" class="btn btn-lg btn-outline-danger w-100 mx-0">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-outline-danger w-100 mx-0">Delete</button>
              </form>
              <a href="{% url 'akromdev:audio-detail' audio.slug %}" class="btn btn-lg btn-outline-secondary w-100 mx-0 mb-2">Cansel</a>
            </div>
          </div>
        </div>
      </div>
</div>
{% endblock %}

templates/audio/audio-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ audio.title }} {% endblock %}

{% block content %}
<div class="modal position-static d-block py-5" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-5 shadow bg-light">
        <div class="modal-header border-bottom-0">
            <img src="{{ audio.cover.url }}" alt="" class="img-fluid" style="border-radius: 7px;">
        </div>
        <div class="modal-body p-4 pt-1">
            <h2 class="fw-bold">{{ audio.title }}</h2>
            {% if audio.description %}
                <h5 class="modal-title">{{ audio_description_html|safe }}</h5>
            {% endif %}
            <br>
            <div class="mt-1 mb-1">
                <a href="{% url 'users:user-profile' audio.author.username %}" class="nav-link text-dark">
                    {{ audio.author.first_name }} {{ audio.author.last_name }}
                </a>
            </div>
            <div align="center" class="bd-example">
                <div class="">
                    
                    <audio src="{{ audio.audio.url }}" style="width: 100%;" autoplay controls></audio>
                    
                    <a href="{{ audio.audio.url }}" class="w-100 py-2 mb-2 btn btn-outline-dark rounded-4" type="submit" download="">
                        download
                    </a>
                    {% if request.user.account.first == audio.author %}
                        <a href="{% url 'akromdev:audio-update' audio.slug %}" class="w-100 py-2 mb-2 btn btn-outline-success rounded-4" type="submit">
                            Update
                        </a>
                        <a href="{% url 'akromdev:audio-delete' audio.slug %}" class="w-100 py-2 mb-2 btn btn-outline-danger rounded-4" type="submit">
                            Delete
                        </a>
                    {% endif %}
                </div>
                <div align="right">
                </div>
            </div>
        </div>
      </div>
    </div>
</div>

<div class="container">
    <div class="row" data-masonry="{&quot;percentPosition&quot;: true }">
        {% for audio in audios %}
            <div class="col-sm-6 col-lg-4 mb-4">
            <div class="card">
                <a href="{% url 'akromdev:audio-detail' audio.slug %}">
                <img src="{{ audio.cover.url }}" alt="img" class="bd-placeholder-img card-img-top img-fluid" width="100%" height="200" role="img">
                </a>
                <div class="card-body">
                <h5 class="card-title">{{ audio.title }}</h5>
                <p class="card-text">
                    <a href="{% url 'users:user-profile' audio.author.username %}" class="nav-link text-dark">
                    <img src="{{ audio.author.avatar.url }}" alt="img" width="40px" height="40px" style="border-radius: 50%;">
                    <span>
                        {{ audio.author.last_name }} {{ audio.author.first_name }}
                    </span>
                    </a>
                </p>
                </div>
            </div>
            </div>
        {% empty %}
            <div align="center">
                <h1>Now Audios</h1>
            </div>
        {% endfor %}
      
    </div>
</div>
{% endblock %}

templates/audio/audio-update.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ audio.title }} Update {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="col-md-10 mx-auto col-lg-5">
      <div class="modal-header p-5 pb-4 border-bottom-0 bg-light">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h3 class="fw-bold mb-0">`{{ audio.title }}` Update</h3>
        <a href="{% url 'akromdev:audio-detail' audio.slug %}" class="btn-close" ></a>
      </div>
        <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'akromdev:audio-update' audio.slug %}" method="POST">
            {% csrf_token %}
          <div class="form-floating mb-3">
            {{ form.title }}
            <label for="floatingInput">title</label>
            <div class="invalid-feedback">
              Enter valid title
            </div>
          </div>

          <div class="form-floating mb-3">
            {{ form.description }}
            <label for="floatingInput">Description</label>
            <div class="invalid-feedback">
              Enter valid description
            </div>
          </div>

          <div class="form-floating mb-3">
            {{ form.category }}
            <div class="invalid-feedback">
              Enter valid category
            </div>
          </div>
          <div>
            <button class="w-100 btn btn-lg btn-primary mt-5" type="submit">Update</button>
            <a href="{% url 'akromdev:audio-detail' audio.slug %}" class="btn btn-lg btn-outline-secondary w-100 mx-0 mb-2 mt-3">Cansel</a>

          </div>
          <!-- <hr class="my-4"> -->

        </form>

      </div>
</div>
{% endblock %}

templates/audio/audios.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Audios {% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'aos/aos.css' %}">
{% endblock %}
{% block content %}
<div class="p-5 mb-4 bg-dark rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Musikalar</h1>
      <p class="col-md-8 fs-4">Eng sara musikalarni faqat bizda tinglang barcha qulayliklar faqat bitta obunada <a href="{% url 'users:sign-up' %}" class="nav-link text-white">Sign Up</a>
    </div>
</div>
<div class="container"> 
  <div class="row" data-masonry="{&quot;percentPosition&quot;: true }">
    {% for audio in audios %}
      <div class="col-sm-6 col-lg-4 mb-4">
        <div class="card">
          <a href="{% url 'akromdev:audio-detail' audio.slug %}">
            <img src="{{ audio.cover.url }}" alt="img" class="bd-placeholder-img card-img-top img-fluid" width="100%" height="200" role="img">
          </a>
          <div class="card-body">
            <h5 class="card-title">{{ audio.title }}</h5>
            <p class="card-text">
              <a href="{% url 'users:user-profile' audio.author.username %}" class="nav-link text-dark">
                <img src="{{ audio.author.avatar.url }}" alt="img" width="40px" height="40px" style="border-radius: 50%;">
                <span>
                  {{ audio.author.first_name }} {{ audio.author.last_name }}
                </span>
              </a>
            </p>
          </div>
        </div>
      </div>
    {% empty %}
      <h1>Now Audios</h1>
    {% endfor %}
  </div>
</div>

{% block script %}
{% endblock %}
{% endblock %}