apps/akromdev/urls.py
from django.urls import path
from .views.home_view import IndexView
from .views.contact_view import ContactView
from .views.about_view import AboutView

from .views.video_view import (
    VideoView,
    VideoDetailView,
    VideoCreateView,
    VideoDeleteView,
    VideoUpdateView,
    video_like,
)
from .views.picture_view import (
    PictureView,
    PictureDetailView,
    PictureCreateView,
    PictureDeleteView,
    PictureUpdateView,
)
from .views.audio_view import (
    AudioView,
    AudioDetailView,
    AudioCreateView,
    AudioUpdateView,
    AudioDeleteView,
)
from .views.blog_view import (
    BlogPostDetailView,
    BlogPostView,
    UserPostView,
    PostUpdateView,
    PostDeleteView,
    PostCreateView,
)


app_name = "akromdev"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("about/", AboutView.as_view(), name="about"),
    path("pictures/", PictureView.as_view(), name="pictures"),
    path("picture-create/", PictureCreateView.as_view(), name="picture-create"),
    path(
        "picture-detail/<str:slug>", PictureDetailView.as_view(), name="picture-detail"
    ),
    path(
        "picture-update/<str:slug>", PictureUpdateView.as_view(), name="picture-update"
    ),
    path(
        "picture-delete/<str:slug>", PictureDeleteView.as_view(), name="picture-delete"
    ),
    path("blog-posts/", BlogPostView.as_view(), name="posts"),
    path(
        "blog-post-detail/<str:slug>", BlogPostDetailView.as_view(), name="post-detail"
    ),
    path("user-posts/<str:username>", UserPostView.as_view(), name="user-posts"),
    path("post-update/<str:slug>", PostUpdateView.as_view(), name="post-update"),
    path("post-delete/<str:slug>", PostDeleteView.as_view(), name="post-delete"),
    path("post-create/", PostCreateView.as_view(), name="post-create"),
    path("videos/", VideoView.as_view(), name="videos"),
    path("video-create/", VideoCreateView.as_view(), name="video-create"),
    path("video-detail/<str:slug>", VideoDetailView.as_view(), name="video-detail"),
    path("video-update/<str:slug>", VideoUpdateView.as_view(), name="video-update"),
    path("video-delete/<str:slug>", VideoDeleteView.as_view(), name="video-delete"),
    path("video-like/<str:slug>", video_like, name="video-like"),
    path("audios/", AudioView.as_view(), name="audios"),
    path("audio-create/", AudioCreateView.as_view(), name="audio-create"),
    path("audio-detail/<str:slug>", AudioDetailView.as_view(), name="audio-detail"),
    path("audio-update/<str:slug>", AudioUpdateView.as_view(), name="audio-update"),
    path("audio-delete/<str:slug>", AudioDeleteView.as_view(), name="audio-delete"),
]

apps/users/urls.py
from django.urls import path
from .views import (
    SignUpView,
    SignInView,
    SignOutView,
    UserAccountView,
    UserProfileView,
    user_follow,
    user_unfollow,
    user_folowers,
    user_folowings,
)


app_name = "users"

urlpatterns = [
    path("sign_up/", SignUpView.as_view(), name="sign-up"),
    path("sign-in/", SignInView.as_view(), name="sign-in"),
    path("sign-out/", SignOutView.as_view(), name="sign-out"),
    path("akromdev-user-account/", UserAccountView.as_view(), name="user-account"),
    path(
        "akromdev-user-profile/<str:username>",
        UserProfileView.as_view(),
        name="user-profile",
    ),
    path("user-follow/<str:username>", user_follow, name="user-follow"),
    path("user-unfollow/<str:username>", user_unfollow, name="user-unfollow"),
    path("user-folowers/<str:username>", user_folowers, name="user-folowers"),
    path("user-folowings/<str:username>", user_folowings, name="user-folowings"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from graphene_django.views import GraphQLView

from .swagger_schema import swagger_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls, name="admin_panel"),
    path("", include("apps.akromdev.urls")),
    path("users/", include("apps.users.urls")),
    path("graphql/", GraphQLView.as_view(graphiql=True)),
]

urlpatterns += swagger_urlpatterns

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/akromdev/forms/contact_form.py
from django import forms
from apps.akromdev.models.contact_model import Contact


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "your name...",
            }
        )
    )
    subject = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "your subject...",
            }
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "type": "email",
                "class": "form-control",
                "placeholder": "your email",
            }
        )
    )
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "name": "message",
                "id": "message",
                "class": "form-control",
                "placeholder": "message...",
            }
        )
    )

    class Meta:
        model = Contact
        fields = ("name", "email", "subject", "message")

apps/akromdev/views/about_view.py
from django.views.generic import TemplateView


class AboutView(TemplateView):
    template_name = "about.html"

apps/akromdev/views/contact_view.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib import messages

from apps.akromdev.forms.contact_form import ContactForm
from apps.akromdev.tasks import send_email_task


class ContactView(View):
    def get(self, request):
        form = ContactForm()
        return render(request, "contact.html", {"form": form})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            subject = form.cleaned_data.get("subject")
            message = form.cleaned_data.get("message")
            email = form.cleaned_data.get("email")

            send_email_task(subject, message, email)

            messages.success(request, "Successfully sending message")
            return redirect("akromdev:contact")

        messages.error(request, "Your sending message is are not valid !")
        return redirect("akromdev:contact")

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About {% endblock %}
{% block content %}

<div class="text-muted">
    <!-- <img src="{% static 'img/banner-2.jpg' %}" alt="img" class="img-fluid"> -->
</div>

<div class="container marketing">

    <hr class="featurette-divider">

    <div class="row featurette tm-telegram">
    
        <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Akrom Rustamov
            <span class="text-muted"> 
                Python Developer
            </span>
        </h2>

        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
        </div>
        <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

        </div>
    </div>

    <hr class="featurette-divider">
  </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/carousel/">
        <!-- Bootstrap core CSS -->
    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/footers.css' %}" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body> 
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">

        <a href="{% url 'akromdev:home' %}" class="navbar-brand d-flex align-items-center">
            <img src="{% static 'img/site-icon.png'%}" alt="icon-img" width="25" height="25" style="border-radius: 50%;">
        </a>

        <a class="navbar-brand" href="{% url 'akromdev:home' %}">
            <b>Akrom<b>Dev</b></b>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'akromdev:about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'akromdev:videos' %}">Videos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'akromdev:audios' %}">Audios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'akromdev:pictures' %}" >Pictures</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'akromdev:contact' %}">Contacts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'akromdev:posts' %}">Blogs</a>
            </li>
        </ul>

        <!-- <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle show" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                
                <img src="{{ request.user.account.first.avatar.url }}" alt="avatar" width="29" height="29" style="border-radius: 50%;">
              </a>
              <ul class="dropdown-menu show" aria-labelledby="navbarDropdown" data-bs-popper="none">
                <li><a class="dropdown-item" href="{% url 'users:user-account' %}">Account</a></li>
                <li><a class="dropdown-item" href="{% url 'users:user-profile' request.user.account.first.username %}">You`r profile</a></li>
                <li><a class="dropdown-item" href="{% url 'akromdev:video-create' %}">add Video</a></li>
                <li><a class="dropdown-item" href="{% url 'akromdev:audio-create' %}">add Audio</a></li>
                <li><a class="dropdown-item" href="{% url 'akromdev:picture-create' %}">add Photo</a></li>
                <li><a class="dropdown-item" href="{% url 'akromdev:post-create' %}">add Post</a></li>

                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'users:sign-out' %}">Sign Out ></a></li>
              </ul>
            </li>
          {% else %}
              <li class="nav-item">
                  <a class="nav-link active" href="{% url 'users:sign-in' %}"><b>Sign In</b></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link active" href="{% url 'users:sign-up' %}"><b>Sign Up</b></a>
              </li>
          {% endif %}
        </ul>
        </div>
    </div>
    </nav>
</header>

{% if messages %}
  {% for message in messages %}
  <div class="bd-example">
    {% if message.tags == 'error' %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% else %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %}
    </div>
  {% endfor %}
{% endif %}

<body>
    {% block content %}
    {% endblock %}
</body>
<div class="container">
    <footer class="py-5">
      <div class="row">
        <div class="col-2">
          <h5><b>Our Pages</b></h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="{% url 'akromdev:home' %}" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Videos</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Contacts</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Blogs</a></li>
          </ul>
        </div>
  
        <div class="col-2">
          <h5><b>Socials</b></h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Telegram</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Instagram</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Facebook</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">GitHub</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">LinkedIn</a></li>
          </ul>
        </div>
  
        <div class="col-4 offset-1">
          <form>
            <h5>Subscribe to our newsletter</h5>
            <p>Monthly digest of whats new and exciting from us.</p>
            <div class="d-flex w-100 gap-2">
              <label for="newsletter1" class="visually-hidden">Email address</label>
              <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
              <button class="btn btn-primary" type="button">Subscribe</button>
            </div>
          </form>
        </div>
      </div>
  
      <div class="d-flex justify-content-between py-4 my-4 border-top">
        <p>© 2021 Company, Inc. All rights reserved.</p>
        <ul class="list-unstyled d-flex">
          <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
          <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
          <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
      </div>
    </footer>
  </div>
  {% block script %}
  {% endblock %}
<script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/dist/js/bootstrap.min.js' %}"></script>
</body>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Contact {% endblock %}
{% block content %}
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">Vertically centered hero sign-up form</h1>
        <p class="col-lg-10 fs-4">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
      </div>

      <div class="col-md-10 mx-auto col-lg-5">

        <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'akromdev:contact' %}" method="POST">
          {% csrf_token %}
          <div class="form-floating mb-3">
            {{ form.name }}
            <label for="floatingInput">Name</label>
          </div>

          <div class="form-floating mb-3">
            {{ form.subject }}
            <label for="floatingInput">Subject</label>
          </div>

          <div class="form-floating mb-3">
            {{ form.email }}
            <label for="floatingInput">Email address</label>
          </div>

          <div class="form-floating mb-3">
            {{ form.message }}
          </div>

          <button class="w-100 btn btn-lg btn-primary" type="submit">Send</button>
          <hr class="my-4">

          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
        </form>

      </div>
    </div>
  </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %} AkromDev {% endblock %}
{% block content %}

<main>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active" aria-current="true"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
  </div>
  <div class="carousel-inner">
      <div class="carousel-item">

      <img src="{% static 'img/corusel-img-1.jpg' %}" alt="corusel-img" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true">
      <div class="container">
          <div class="carousel-caption text-start">
          <h1>Example headline.</h1>
          <p>translate "Some representative placeholder content for the first slide of the carousel.</p>
          <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
      </div>
      </div>
      <div class="carousel-item active">

      <img src="{% static 'img/corusel-img-2.jpg' %}" alt="corusel-img" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true">
      <div class="container">
          <div class="carousel-caption">
          <h1>Another example headline.</h1>
          <p>Some representative placeholder content for the second slide of the carousel.</p>
          <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
      </div>
      </div>
      <div class="carousel-item">

      <img src="{% static 'img/corusel-img-3.jpg' %}" alt="corusel-img" class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true">
      <div class="container">
          <div class="carousel-caption text-end">
          <h1>One more for good measure.</h1>
          <p>Some representative placeholder content for the third slide of this carousel.</p>
          <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
      </div>
      </div>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
  </button>

  <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
  </button>
  </div>

  <div class="container marketing">

    <!-- <div class="row">
        <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
        </div>
        <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
        </div>
        <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
        </div>
    </div> -->

    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
        </div>
        <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
        </div>
        <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

        </div>
    </div>
    <div class="parallax-window parallax-window-2" data-parallax="scroll" data-image-src="{% static 'img/site-icon.png' %}"></div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
        </div>
        <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

        </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div>

</main>
{% endblock %}