apps/akromdev/urls.py
from django.urls import path
from .views.home_view import IndexView
from .views.contact_view import ContactView
from .views.about_view import AboutView

from .views.video_view import (
    VideoView,
    VideoDetailView,
    VideoCreateView,
    VideoDeleteView,
    VideoUpdateView,
    video_like,
)
from .views.picture_view import (
    PictureView,
    PictureDetailView,
    PictureCreateView,
    PictureDeleteView,
    PictureUpdateView,
)
from .views.audio_view import (
    AudioView,
    AudioDetailView,
    AudioCreateView,
    AudioUpdateView,
    AudioDeleteView,
)
from .views.blog_view import (
    BlogPostDetailView,
    BlogPostView,
    UserPostView,
    PostUpdateView,
    PostDeleteView,
    PostCreateView,
)


app_name = "akromdev"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("about/", AboutView.as_view(), name="about"),
    path("pictures/", PictureView.as_view(), name="pictures"),
    path("picture-create/", PictureCreateView.as_view(), name="picture-create"),
    path(
        "picture-detail/<str:slug>", PictureDetailView.as_view(), name="picture-detail"
    ),
    path(
        "picture-update/<str:slug>", PictureUpdateView.as_view(), name="picture-update"
    ),
    path(
        "picture-delete/<str:slug>", PictureDeleteView.as_view(), name="picture-delete"
    ),
    path("blog-posts/", BlogPostView.as_view(), name="posts"),
    path(
        "blog-post-detail/<str:slug>", BlogPostDetailView.as_view(), name="post-detail"
    ),
    path("user-posts/<str:username>", UserPostView.as_view(), name="user-posts"),
    path("post-update/<str:slug>", PostUpdateView.as_view(), name="post-update"),
    path("post-delete/<str:slug>", PostDeleteView.as_view(), name="post-delete"),
    path("post-create/", PostCreateView.as_view(), name="post-create"),
    path("videos/", VideoView.as_view(), name="videos"),
    path("video-create/", VideoCreateView.as_view(), name="video-create"),
    path("video-detail/<str:slug>", VideoDetailView.as_view(), name="video-detail"),
    path("video-update/<str:slug>", VideoUpdateView.as_view(), name="video-update"),
    path("video-delete/<str:slug>", VideoDeleteView.as_view(), name="video-delete"),
    path("video-like/<str:slug>", video_like, name="video-like"),
    path("audios/", AudioView.as_view(), name="audios"),
    path("audio-create/", AudioCreateView.as_view(), name="audio-create"),
    path("audio-detail/<str:slug>", AudioDetailView.as_view(), name="audio-detail"),
    path("audio-update/<str:slug>", AudioUpdateView.as_view(), name="audio-update"),
    path("audio-delete/<str:slug>", AudioDeleteView.as_view(), name="audio-delete"),
]

apps/users/urls.py
from django.urls import path
from .views import (
    SignUpView,
    SignInView,
    SignOutView,
    UserAccountView,
    UserProfileView,
    user_follow,
    user_unfollow,
    user_folowers,
    user_folowings,
)


app_name = "users"

urlpatterns = [
    path("sign_up/", SignUpView.as_view(), name="sign-up"),
    path("sign-in/", SignInView.as_view(), name="sign-in"),
    path("sign-out/", SignOutView.as_view(), name="sign-out"),
    path("akromdev-user-account/", UserAccountView.as_view(), name="user-account"),
    path(
        "akromdev-user-profile/<str:username>",
        UserProfileView.as_view(),
        name="user-profile",
    ),
    path("user-follow/<str:username>", user_follow, name="user-follow"),
    path("user-unfollow/<str:username>", user_unfollow, name="user-unfollow"),
    path("user-folowers/<str:username>", user_folowers, name="user-folowers"),
    path("user-folowings/<str:username>", user_folowings, name="user-folowings"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from graphene_django.views import GraphQLView

from .swagger_schema import swagger_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls, name="admin_panel"),
    path("", include("apps.akromdev.urls")),
    path("users/", include("apps.users.urls")),
    path("graphql/", GraphQLView.as_view(graphiql=True)),
]

urlpatterns += swagger_urlpatterns

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models/user_model.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from apps.users.utils import generate_token

 
class User(AbstractUser):
    token = models.CharField(
        max_length=200,
        unique=True,
        help_text=_("Required. 200 charecters unique !"),
        error_messages={"unique": _("A user with that token already exists")},
        db_index=True,
    )
    folowings = models.ManyToManyField(
        "self", symmetrical=False, related_name="folowers", blank=True, db_index=True
    )

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")
        db_table = "users"

    def save(self, *args, **kwargs):
        self.token = generate_token(100)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.username


__all__ = ("User",)

apps/users/models/useraccountsocialurl.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.shared.models import AbstractBaseModel


class UserAccountSocialUrl(AbstractBaseModel):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, blank=True, null=True)
    url = models.URLField()

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Account social url")
        verbose_name_plural = _("Account social urls")
        db_table = "user_account_social_urls"


__all__ = ("UserAccountSocialUrl",)

apps/users/forms/signin_form.py
from django import forms
from django.core.exceptions import ValidationError
from apps.users.models.useraccount_model import UserAccount
from apps.users.models.user_model import User


class SignInForm(forms.ModelForm):
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control rounded-4",
                "placeholder": "First name...",
            }
        ),
    )
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control rounded-4",
                "placeholder": "Last name...",
            }
        ),
    )
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control rounded-4",
                "placeholder": "Username...",
            }
        ),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "type": "email",
                "class": "form-control rounded-4",
                "placeholder": "Email...",
            }
        ),
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "type": "password",
                "class": "form-control rounded-4",
                "placeholder": "Password...",
            }
        ),
    )
    password_change = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "type": "password",
                "class": "form-control rounded-4",
                "placeholder": "Password (Change)...",
            }
        ),
    )

    def save(self, commit=True):
        user = super().save(commit)
        password = self.cleaned_data.get("password")
        password_change = self.cleaned_data.get("password_change")

        if password == password_change:
            user.set_password(password)
            user.save()
            UserAccount.objects.create(
                user=user,
                first_name=user.first_name,
                last_name=user.last_name,
                username=user.username,
                email=user.email,
            )

        else:
            raise ValidationError("password and password_change must be match")

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password",
            "password_change",
        )


__all__ = ("SignInForm",)

apps/users/forms/signup_form.py
from django import forms


class SignUpForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control rounded-4",
                "id": "floatingInput",
                "placeholder": "Email or Username...",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "type": "password",
                "class": "form-control rounded-4",
                "id": "floatingPassword",
                "placeholder": "Password...",
            }
        )
    )


__all__ = ("SignUpForm",)

apps/users/views/signin_view.py
from django.views import View
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from apps.users.forms.signin_form import SignInForm


class SignInView(View):
    def get(self, request):
        form = SignInForm()
        return render(request, "user/sign_in.html", {"form": form})

    def post(self, request):
        form = SignInForm(request.POST)

        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data.get("username"),
                password=form.cleaned_data.get("password"),
            )
            login(request, user)

            messages.success(request, f"Successfully registered {user.username}")
            return redirect(reverse("akromdev:home"))

        messages.error(request, "Your fields are nov valid !")
        return redirect(reverse("users:sign-in"))


__all__ = ("SignInView",)

apps/users/views/signout_view.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


class SignOutView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "user/sign_out.html")

    def post(self, request):
        logout(request)
        messages.info(request, "Sign out on system. ")
        return redirect("akromdev:home")


__all__ = ("SignOutView",)

apps/users/views/signup_view.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from apps.users.forms.signup_form import SignUpForm


class SignUpView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, "user/sign_up.html", {"form": form})

    def post(self, request):
        form = SignUpForm(request.POST)

        if form.is_valid():

            user = authenticate(
                username=form.cleaned_data.get("username"),
                password=form.cleaned_data.get("password"),
            )
            if user:
                login(request, user)
                messages.success(
                    request, f"{request.user.username} you successfully loged"
                )
                return redirect("akromdev:home")

            messages.error(request, "Invalid username or password !")
            return redirect("users:sign-up")

        messages.warning(request, "Your username or password are not valid !")
        return redirect("users:sign-up")


__all__ = ("SignUpView",)

apps/users/views/user_functions.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from apps.users.models.useraccount_model import UserAccount


@login_required
def user_follow(request, username):
    if request.user.is_authenticated:
        if request.method == "POST":
            user_account = get_object_or_404(UserAccount, username=username)
            user_account.follow(request.user)
            return redirect(
                reverse(
                    "users:user-profile", kwargs={"username": user_account.username}
                )
            )

        messages.error(request, "Method not allowed !")
        return redirect("akromdev:home")

    else:
        messages.info(request, "Please Sign up in system !")
        return redirect(reverse("users:sign-up"))


@login_required
def user_unfollow(request, username):
    if request.user.is_authenticated:
        if request.method == "POST":
            user_account = get_object_or_404(UserAccount, username=username)
            user_account.unfollow(request.user)
            return redirect(
                reverse(
                    "users:user-profile", kwargs={"username": user_account.username}
                )
            )

        messages.error(request, "Method not allowed !")
        return redirect("akromdev:home")

    else:
        messages.info(request, "Please Sign up in system !")
        return redirect(reverse("users:sign-up"))


@login_required
def user_folowers(request, username):
    user_account = get_object_or_404(UserAccount, username=username)
    users = user_account.user.folowers.all()
    return render(request, "user/users.html", {"title": "Folowers", "users": users})


@login_required
def user_folowings(request, username):
    user_account = get_object_or_404(UserAccount, username=username)
    users = user_account.user.folowings.all()
    return render(request, "user/users.html", {"title": "Folowings", "users": users})


__all__ = (
    "user_follow",
    "user_unfollow",
    "user_folowers",
    "user_folowings",
)

apps/users/views/useraccount_view.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from apps.users.forms.useraccount_form import UserAccountForm
from apps.users.models.useraccount_model import UserAccount


class UserAccountView(LoginRequiredMixin, View):
    def get(self, request):
        user_account = get_object_or_404(UserAccount, user=request.user)
        form = UserAccountForm(instance=user_account)

        return render(
            request,
            "user/user_account.html",
            {"form": form, "user_account": user_account},
        )

    def post(self, request):
        user_account = get_object_or_404(UserAccount, user=request.user)

        form = UserAccountForm(
            data=request.POST, files=request.FILES, instance=user_account
        )
        if form.is_valid():
            form.save()

            messages.success(
                request, f"Successfully updated your account {request.user.username}"
            )
            return redirect("users:user-account")

        messages.error(request, "You`r fields are not valid !")
        return redirect("users:user-account")


__all__ = ("UserAccountView",)

apps/users/views/userprofile_view.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from apps.users.models import User, UserAccount
from apps.akromdev.models import Video, Picture, Audio


class UserProfileView(View):
    def get(self, request, username):
        if request.user.is_authenticated:
            if username[0] == "@":

                user = get_object_or_404(User, username=username[1:])
                user_account = get_object_or_404(UserAccount, user=user)
                videos = Video.objects.filter(author=user_account).order_by(
                    "-created_at"
                )
                audios = Audio.objects.filter(author=user_account).order_by(
                    "created_at"
                )
                pictures = Picture.objects.filter(author=user_account).order_by(
                    "-created_at"
                )

                return render(
                    request,
                    "user/user_profile.html",
                    {
                        "user_account": user_account,
                        "videos": videos,
                        "audios": audios,
                        "pictures": pictures,
                    },
                )

            messages.error(request, "Now validate username not found '@' ")
            return redirect("akromdev:videos")

        return redirect("users:sign-up")


__all__ = ("UserProfileView",)

templates/user/sign_in.html
{% extends 'base.html' %}
{% block title %} Sign Up {% endblock %}
{% block content %}
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-5 shadow">
        <div class="modal-header p-5 pb-4 border-bottom-0">
          <h2 class="center">Sign In</h2>
        </div>
  
        <div class="modal-body p-5 pt-0">
          <form method="POST" accept="{% url 'users:sign-in'%}">
            {% csrf_token %}
            <div class="form-floating mb-3">
              {{ form.first_name }}
              <label for="floatingInput">First Name</label>
            </div>

            <div class="form-floating mb-3">
              {{ form.last_name }}
              <label for="floatingInput">First Name</label>
            </div>

            <div class="form-floating mb-3">
              {{ form.username }}
              <label for="floatingInput">Username</label>
            </div>

            <div class="form-floating mb-3">
              {{ form.email }}
              <label for="floatingInput">Email Address</label>
            </div>

            <div class="form-floating mb-3">
              {{ form.password }}
              <label for="floatingPassword">Password</label>
            </div>

            <div class="form-floating mb-3">
              {{ form.password_change }}
              <label for="floatingPassword">Password ( Сchange )</label>
            </div>

            <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Sign In</button>

            <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
            <hr class="my-4">

            <h2 class="fs-5 fw-bold mb-3">Or use a third-party</h2>

            <button class="w-100 py-2 mb-2 btn btn-outline-dark rounded-4" type="submit">
              <use xlink:href="#Google"></use></svg>
              Sign up with Google
            </button>

          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/user/sign_out.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<div class="modal modal-alert position-static d-block  py-5" tabindex="-1" role="dialog" id="modalChoice">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-body p-4 text-center">
          <h5 class="mb-0">You are log out ?</h5>
          <p class="mb-0">Siz sistemadan chiqib ketmoqchimisiz ?.</p>
        </div>
        <form action="{% url 'users:sign-out' %}" method="post">
          {% csrf_token %}
          <div class="modal-footer flex-nowrap p-0">
            <button type="submit" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 m-0 rounded-0 border-right"><strong>Yes / Ha</strong></button>
            <a href="{% url 'akromdev:home' %}" type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 m-0 rounded-0" data-bs-dismiss="modal">No / Yo`q</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/user/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Sign Up {% endblock %}
{% block content %}
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-5 shadow">
        <div class="modal-header p-5 pb-4 border-bottom-0">
          <!-- <h5 class="modal-title">Modal title</h5> -->
          <h2 class="center">Sign up</h2>
        </div>
  
        <div class="modal-body p-5 pt-0">
          <form accept="{% url 'users:sign-up' %}" method="POST">
            {% csrf_token %}
            <div class="form-floating mb-3">
              {{ form.username }}
              <label for="floatingInput">Email address or Username</label>
            </div>

            <div class="form-floating mb-3">
              {{ form.password }}
              <label for="floatingPassword">Password</label>
              
            </div>

            <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Sign up</button>

            <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
            <hr class="my-4">

            <h2 class="fs-5 fw-bold mb-3">Or use a third-party</h2>

            <button class="w-100 py-2 mb-2 btn btn-outline-dark rounded-4" type="submit">
              <svg class="bi me-1" width="16" height="16"><use xlink:href="#google"></use></svg>
              Sign up with Google
            </button>

          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/user/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile  {% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="row featurette">
        <img src="{{ user_account.bg_cover.url }}" alt="img" class="bd-placeholder-img bd-placeholder-img-lg" width="100%" height="250">

        <div class="col-md-7">
            <div class="bd-example">
                <!-- <svg class="bd-placeholder-img bd-placeholder-img-lg img-fluid" width="100%" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Responsive image" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"></rect><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Responsive image</text></svg> -->
                <div class="col-lg-4">
                    <img src="{{ user_account.avatar.url }}" class="bd-placeholder-img rounded-circle mt-5" width="140" height="140"  role="img" focusable="false">
                
                    <h2>{{ user_account.first_name }} {{ user_account.last_name }}</h2>
                    {% if user_account.bio %}
                        <p>{{ user_account.bio }}</p>
                    {% endif %}
                    <div class="bd-example">
                      {% if request.user != user_account.user %}
                        {% if request.user in user_account.user.folowings.all %}
                          <form action="{% url 'users:user-unfollow' user_account.username %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-secondary">Unfollow</button>
                          </form>
                        {% else %}
                          <form action="{% url 'users:user-follow' user_account.username %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-secondary">Folow</button>
                          </form>
                        {% endif %}
                      {% else %}
                      <a href="{% url 'users:user-account' %}" type="submit" class="btn btn-outline-secondary">Update profile</a>
                      <a href="" type="submit" class="btn btn-outline-secondary">Share profile</a>
                      {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5 mt-5">
            <!-- right content -->
            <div class="modal-body p-4 text-center">
              <h5 class="mb-0">Enable this setting?</h5>
              <p class="mb-7">
                {% if user_account.socials %}
                  {% for social in user_account.socials.all %}
                    <a href="{{ social.url }}" class="nav-link text-dark">{{ social.name }}</a>
                  {% endfor %}
                {% endif %}
              </p>
            </div>
            <div class="modal-footer flex-nowrap p-0 text-center">
                <a href="{% url 'users:user-folowers' user_account.username %}" class="nav-link text-dark">
                  <h3>{{ user_account.user.folowers.all.count }} folowers</h3>
                </a>
                <a href="{% url 'users:user-folowings' user_account.username %}" class="nav-link text-dark">
                  <h3>{{ user_account.user.folowings.all.count }} folowings</h3>
                </a>
            </div>
          </div>

        </div>
        <div class="container mt-5 mb-5">
            <div class="bd-example">
                <nav>
                  <div class="nav nav-tabs mb-3" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-videos-tab" data-bs-toggle="tab" data-bs-target="#nav-videos" type="button" role="tab" aria-controls="nav-videos" aria-selected="true">Videos</button>
                    <button class="nav-link" id="nav-audios-tab" data-bs-toggle="tab" data-bs-target="#nav-audios" type="button" role="tab" aria-controls="nav-audios" aria-selected="false">Audios</button>
                    <button class="nav-link" id="nav-photos-tab" data-bs-toggle="tab" data-bs-target="#nav-photos" type="button" role="tab" aria-controls="nav-photos" aria-selected="false">Photos</button>
                  </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                  <div class="tab-pane fade active show" id="nav-videos" role="tabpanel" aria-labelledby="nav-videos-tab">

                    <div class="row" data-masonry="{&quot;percentPosition&quot;: true }">
                      {% if videos %}
                        {% for video in videos %}
                          <div class="col-sm-6 col-lg-4 mb-4">
                            <div class=" overflow-hidden text-dark bg-white rounded-5 shadown-lg">
                              <!-- <svg class="bd-placeholder-img card-img" width="100%" height="260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Card image" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"></rect><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Card image</text></svg> -->
                              <a href="{% url 'akromdev:video-detail' video.slug %}">
                                <img src="{{ video.cover.url }}" alt="" width="100%" height="260" role="img" style="border-radius: 5%;">
                              </a>
                              <div class="mt-2">
                                <p>
                                  <b>{{ video.title }}</b>
                                </p>
                                <a href="#" class="nav-link text-dark">
                                  <small>{{ video.created_at }}</small>
                                </a>
                              </div>
                            </div>
                          </div>
                        {% empty %}
                          <h1>Now VIdoes</h1>
                        {% endfor %}
                      {% endif %}
                    </div>

                  </div>
                  <div class="tab-pane fade" id="nav-audios" role="tabpanel" aria-labelledby="nav-audios-tab">
                    {% if audios %}
                    <div class="container"> 
                      <div class="row" data-masonry="{&quot;percentPosition&quot;: true }">
                        {% for audio in audios %}
                          <div class="col-sm-6 col-lg-4 mb-4">
                            <div class="card">
                              <a href="{% url 'akromdev:audio-detail' audio.slug %}">
                                <img src="{{ audio.cover.url }}" alt="img" class="bd-placeholder-img card-img-top img-fluid" width="100%" height="200" role="img">
                              </a>
                              <div class="card-body">
                                <h5 class="card-title">{{ audio.title }}</h5>
                                <p class="card-text">
                                  <a href="#" class="nav-link text-dark">
                                    {{ audio.created_at }}
                                  </a>
                                </p>
                              </div>
                            </div>
                          </div>
                        {% empty %}
                          <h1>Now Audios</h1>
                        {% endfor %}
                      </div>
                    </div>
                    {% endif %}
                    
                  </div>
                  <div class="tab-pane fade" id="nav-photos" role="tabpanel" aria-labelledby="nav-photos-tab">
                  
                    <div class="row" data-masonry="{&quot;percentPosition&quot;: true }">
                      {% if pictures %}
                        {% for picture in pictures %}
                          <div class="col-sm-6 col-lg-4 mb-4">
                            <div class="card">
                              <a href="{% url 'akromdev:picture-detail' picture.slug %}">
                                <img src="{{ picture.image.url }}" alt="img" class="bd-placeholder-img card-img" width="100%" height="260" role="img">
                              </a>
                              {% if picture.description %}
                                  {{ picture.description }}
                              {% endif %}
                            </div>
                          </div>
                        {% empty %}
                          <h1>Now Pictures</h1>
                        {% endfor %}
                      {% endif %}

                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/users.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row">
      {% for user in users %}
        <div class="col-lg-4">
          <img src="{{ user.account.first.avatar.url }}" alt="img" class="bd-placeholder-img rounded-circle" width="140" height="140" role="img">
          <h2>{{ user.account.first.first_name }} {{ user.account.first.last_name }}</h2>
          {% if user.account.first.bio %}
            <p>{{ user.account.first.bio }}</p>
          {% endif %}
          <p><a class="btn btn-secondary" href="{% url 'users:user-profile' user.account.first.username %}">Go to profile »</a></p>
        </div><!-- /.col-lg-4 -->
      {% empty %}
      <center><h1>Now Users</h1></center>
      {% endfor %}
      </div>
</div>
{% endblock %}